"""
This type stub file was generated by pyright.
"""

MODULE_PATH = ...
AUDIO_DIR = ...
def run_all(countdown=...): # -> None:
    ...

class FunctionCheckBase:
    @classmethod
    def run(cls, countdown=...): # -> None:
        ...
    


class LeftRightCheck(FunctionCheckBase):
    """
    Checks stereo playback by first playing a note in the left channel only,
    then a different note in the right channel only.
    """
    ...


class OverlappingCheck(FunctionCheckBase):
    """
    Checks overlapped playback by playing three different notes spaced
    approximately a half-second apart but still overlapping.
    """
    ...


class StopCheck(FunctionCheckBase):
    """
    Checks stopping playback by playing three different notes simultaneously
    and stopping two after approximately a half-second, leaving only one note
    playing for two more seconds.
    """
    ...


class StopAllCheck(FunctionCheckBase):
    """
    Checks stopping playback of all audio by playing three different notes
    simultaneously and stopping all of them after approximately a half-second.
    """
    ...


class IsPlayingCheck(FunctionCheckBase):
    """
    Checks functionality of the is_playing() method by calling during playback
    (when it should return True) and calling it again after all playback has
    stopped (when it should return False). The output is printed.
    """
    ...


class WaitDoneCheck(FunctionCheckBase):
    """
    Checks functionality of the wait_done() method by using it to allow the
    three-note clip to play until finished (before attempting to stop
    playback).
    """
    ...


if __name__ == "__main__":
    ...
