"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt

class WaveObject:
    def __init__(self, audio_data, num_channels=..., bytes_per_sample=..., sample_rate=...) -> None:
        ...
    
    def play(self): # -> PlayObject:
        ...
    
    @classmethod
    def from_wave_file(cls, wave_file): # -> Self:
        ...
    
    @classmethod
    def from_wave_read(cls, wave_read): # -> Self:
        ...
    
    def __str__(self) -> str:
        ...
    


class PlayObject:
    #def __init__(self, play_id) -> None:
    #    ...
    
    def stop(self) -> None:
        ...
    
    def wait_done(self) -> None:
        ...
    
    def is_playing(self) -> bool:
        ...
    


def stop_all() -> None:
    ...

#cast(audio.play_buffer, Callable[[NDArray[np.int16], int, int, int], None])

def play_buffer(
        audio_data: npt.NDArray[np.int16],
        num_channels: int,
        bytes_per_sample: int,
        sample_rate: int, 
        ) -> PlayObject:
    ...

