from backend.interface.colours import (
    Palette,
    PalettePair,
)

DEFAULT_LOAD_POINT: int = 0x8000
EMULATED_MIKEOS_VERSION: int = 18
EMULATED_MIKEOS_VERSION_STRING: str = '4.7.0'
EMULATED_MIKEOS_COMMAND_LIST: list[str] = [
    'DIR', 'LS', 'COPY', 'REN', 'DEL', 'CAT', 'SIZE', 'CLS', 'HELP',
    'TIME', 'DATE', 'VER', 'EXIT']
DEFAULT_NUMERIC_VARIABLES_LOCATION: int = 0x4000
DEFAULT_STRING_VARIABLES_LOCATION: int = 0x4100
DEFAULT_COLUMNS = 80
DEFAULT_LINES = 25
DEFAULT_CHARACTER_WIDTH = 9
DEFAULT_CHARACTER_HEIGHT = 16
DEFAULT_STRING_LENGTH = 127
DEFAULT_BACKGROUND_COLOUR = PalettePair(Palette.LIGHT_GRAY, Palette.BLACK)
DEFAULT_PRINT_COLOUR = DEFAULT_BACKGROUND_COLOUR
DEFAULT_DIALOG_OUTER_COLOUR = PalettePair(Palette.WHITE, Palette.RED)
DEFAULT_DIALOG_INNER_COLOUR = PalettePair(Palette.BLACK, Palette.WHITE)
DEFAULT_DIALOG_SELECTOR_COLOUR = PalettePair(Palette.WHITE, Palette.BLACK)
DEFAULT_LIST_DIALOG_WIDTH = 40
DEFAULT_LIST_DIALOG_HEIGHT = 21
DEFAULT_LIST_DIALOG_X = 20
DEFAULT_LIST_DIALOG_Y = 2
DEFAULT_MESSAGE_DIALOG_WIDTH = 42
DEFAULT_MESSAGE_DIALOG_HEIGHT = 7
DEFAULT_MESSAGE_DIALOG_X = 19
DEFAULT_MESSAGE_DIALOG_Y = 9
DEFAULT_CURSOR_BLINK_INTERVAL = 0.5
DEFAULT_CURSOR_VISIBILITY = True
DEFAULT_CURSOR_BLINK = True
DEFAULT_CURSOR_HEIGHT = 2
DEFAULT_WINDOW_TITLE = 'MikeOS Basic Emulator'
